name: React App Pipeline test

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.HECKIN_SECRET }}
          publish_dir: ./build

      - name: Log pipeline trigger count
        run: echo "pipeline trigger ${{ github.run_number }}"
